# Generated by Django 5.2.4 on 2025-07-10 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MountainLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Montanha')),
                ('min_altitude', models.IntegerField(verbose_name='Altitude Mínima')),
                ('max_altitude', models.IntegerField(verbose_name='Altitude Máxima')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('image', models.ImageField(blank=True, null=True, upload_to='mountains/', verbose_name='Imagem')),
            ],
            options={
                'verbose_name': 'Nível de Montanha',
                'verbose_name_plural': 'Níveis de Montanha',
                'ordering': ['min_altitude'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('tipo', models.CharField(choices=[('resumo', 'Resumo'), ('apostila', 'Apostila'), ('exercicios', 'Lista de Exercícios'), ('prova', 'Prova Antiga'), ('projeto', 'Projeto'), ('artigo', 'Artigo'), ('outros', 'Outros')], max_length=20, verbose_name='Tipo')),
                ('materia', models.CharField(max_length=100, verbose_name='Matéria')),
                ('serie', models.CharField(choices=[('1', '1º Período'), ('2', '2º Período'), ('3', '3º Período'), ('4', '4º Período'), ('5', '5º Período'), ('6', '6º Período'), ('7', '7º Período'), ('8', '8º Período'), ('9', '9º Período'), ('10', '10º Período')], max_length=2, verbose_name='Período')),
                ('arquivo', models.FileField(upload_to='materiais/', verbose_name='Arquivo')),
                ('data_upload', models.DateTimeField(auto_now_add=True, verbose_name='Data de Upload')),
                ('downloads', models.IntegerField(default=0, verbose_name='Downloads')),
                ('aprovacoes', models.IntegerField(default=0, verbose_name='Aprovações')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiais',
                'ordering': ['-data_upload'],
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Comentário')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.material', verbose_name='Material')),
            ],
            options={
                'verbose_name': 'Comentário',
                'verbose_name_plural': 'Comentários',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='MountainAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achieved_at', models.DateTimeField(auto_now_add=True)),
                ('mountain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.mountainlevel')),
            ],
            options={
                'verbose_name': 'Conquista de Montanha',
                'verbose_name_plural': 'Conquistas de Montanha',
                'ordering': ['-achieved_at'],
            },
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('conquista', 'Nova Conquista'), ('comentario', 'Novo Comentário'), ('avaliacao', 'Nova Avaliação'), ('material', 'Novo Material')], max_length=20, verbose_name='Tipo')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('lida', models.BooleanField(default=False, verbose_name='Lida')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=100, verbose_name='Curso')),
                ('altitude_total', models.IntegerField(default=0, verbose_name='Altitude Total')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('montanha_atual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.mountainlevel', verbose_name='Montanha Atual')),
                ('montanhas_conquistadas', models.ManyToManyField(related_name='conquistadores', through='materials.MountainAchievement', to='materials.mountainlevel', verbose_name='Montanhas Conquistadas')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil do Usuário',
                'verbose_name_plural': 'Perfis dos Usuários',
            },
        ),
        migrations.AddField(
            model_name='mountainachievement',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.userprofile'),
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Nota')),
                ('data_avaliacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Avaliação')),
                ('avaliador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Avaliador')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.material', verbose_name='Material')),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
                'ordering': ['-data_avaliacao'],
                'unique_together': {('material', 'avaliador')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='mountainachievement',
            unique_together={('user_profile', 'mountain')},
        ),
    ]
