# Generated by Django 5.2.4 on 2025-07-10 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='destaque',
            field=models.BooleanField(default=False, verbose_name='Material em Destaque'),
        ),
        migrations.AddField(
            model_name='material',
            name='tags',
            field=models.CharField(blank=True, max_length=500, verbose_name='Tags (separadas por vírgula)'),
        ),
        migrations.AddField(
            model_name='material',
            name='visualizacoes',
            field=models.IntegerField(default=0, verbose_name='Visualizações'),
        ),
        migrations.CreateModel(
            name='SocialShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plataforma', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('twitter', 'Twitter'), ('facebook', 'Facebook'), ('email', 'Email'), ('link', 'Link Direto')], max_length=20, verbose_name='Plataforma')),
                ('data_compartilhamento', models.DateTimeField(auto_now_add=True, verbose_name='Data do Compartilhamento')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.material', verbose_name='Material')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Compartilhamento Social',
                'verbose_name_plural': 'Compartilhamentos Sociais',
                'ordering': ['-data_compartilhamento'],
            },
        ),
        migrations.CreateModel(
            name='MaterialFavorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_favoritado', models.DateTimeField(auto_now_add=True, verbose_name='Data Favoritado')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.material', verbose_name='Material')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Material Favorito',
                'verbose_name_plural': 'Materiais Favoritos',
                'ordering': ['-data_favoritado'],
                'unique_together': {('usuario', 'material')},
            },
        ),
    ]
