# Generated by Django 5.2.4 on 2025-07-10 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_material_destaque_material_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='serie',
            field=models.CharField(choices=[('G1', 'G1 (1º Período)'), ('G2', 'G2 (2º Período)'), ('G3', 'G3 (3º Período)'), ('G4', 'G4 (4º Período)'), ('G5', 'G5 (5º Período)'), ('G6', 'G6 (6º Período)'), ('G7', 'G7 (7º Período)'), ('G8', 'G8 (8º Período)'), ('G9', 'G9 (9º Período)'), ('G10', 'G10 (10º Período)')], max_length=3, verbose_name='Período'),
        ),
    ]
