# Generated by Django 5.2.4 on 2025-07-10 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_add_social_chat_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='serie',
        ),
        migrations.AddField(
            model_name='material',
            name='grau',
            field=models.CharField(blank=True, choices=[('G1', 'G1'), ('G2', 'G2'), ('G3', 'G3'), ('G4', 'G4')], max_length=3, verbose_name='Grau'),
        ),
    ]
